// Code generated by protoc-gen-go. DO NOT EDIT.
// This file will be generated by: protoc --go_out=. --go-grpc_out=. proto/report.proto
// For now, this is a placeholder. Run the protoc command to generate the actual file.

package proto

// Placeholder - generate with protoc
